# Generated by Django 2.2 on 2022-02-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_email',
            field=models.CharField(default='无', max_length=30, verbose_name='邮箱'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_phone',
            field=models.CharField(default='无', max_length=30, verbose_name='手机'),
        ),
    ]
